name: owliver-backend-dev

x-common-env: &common-env
  PYTHONPATH: /app
  STAGE: ${INFISICAL_SECRET_ENV}
  ENVIRONMENT: production
  PROJECT_ID: ${PROJECT_ID}
  INFISICAL_SECRET_ENV: ${INFISICAL_SECRET_ENV}
  INFISICAL_API_URL: ${INFISICAL_API_URL}
  INFISICAL_MACHINE_CLIENT_ID: ${INFISICAL_MACHINE_CLIENT_ID}
  INFISICAL_MACHINE_CLIENT_SECRET: ${INFISICAL_MACHINE_CLIENT_SECRET}

services:
  owliver-api:
    image: ghcr.io/xiberty/owliver-ws-dev:${IMAGE_TAG:-latest}
    environment:
      <<: *common-env
      PROCESS_LABEL: api
    command: /start
    ports:
      - "14065:8200"
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true
