name: owliver-backend

services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PROCESS_LABEL=api
      - MAILPIT_API_URL=http://mailpit:8025
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8200:8200"
    volumes:
      - .:/app
    command: /start

  postgres:
    image: postgres:17
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=2MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB

  redis:
    image: redis:7
    ports:
      - "6791:6379"

  mailpit:
    image: axllent/mailpit
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    ports:
      - "8027:8025"
      - "1027:1025"

volumes:
  postgres_data:
