"""initial

Revision ID: d86eebe6b2dd
Revises: 
Create Date: 2026-06-20 02:35:16.192276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd86eebe6b2dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_addresses',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_email_addresses_email'), 'email_addresses', ['email'], unique=True)
    op.create_table('phone_numbers',
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('dial_code', sa.SmallInteger(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('dial_code', 'phone_number', name='uq_phone_numbers_dial_code_phone_number')
    )
    op.create_index(op.f('ix_phone_numbers_dial_code'), 'phone_numbers', ['dial_code'], unique=False)
    op.create_index(op.f('ix_phone_numbers_phone_number'), 'phone_numbers', ['phone_number'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False, comment='Status'),
    sa.Column('time_zone', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=25), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('view_workspace', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('webhook_signature_key', sa.String(length=255), nullable=True),
    sa.Column('plan_slug', sa.String(length=50), server_default='starter', nullable=False),
    sa.Column('monthly_page_quota_override', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_tenants_is_deleted'), 'tenants', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('tenant_api_keys',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('key_hash', name='uq_tenant_api_keys_key_hash')
    )
    op.create_index('ix_tenant_api_keys_tenant', 'tenant_api_keys', ['tenant_id'], unique=False)
    op.create_table('tenant_roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False, comment='Status'),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_tenant_role_tenant_slug')
    )
    op.create_index(op.f('ix_tenant_roles_slug'), 'tenant_roles', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True, comment='Hashed password'),
    sa.Column('email_address_id', sa.UUID(), nullable=True),
    sa.Column('phone_number_id', sa.UUID(), nullable=True),
    sa.Column('current_tenant_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['current_tenant_id'], ['tenants.uuid'], name='fk_current_tenant_id', ondelete='SET NULL', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['email_address_id'], ['email_addresses.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email_address_id', name='uq_users_email_address_id'),
    sa.UniqueConstraint('phone_number_id', name='uq_users_phone_number_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # Deferred FK (circular: tenants.owner_id -> users.uuid). Created after
    # both tables exist; matches the use_alter=True relationship in the ORM.
    op.create_foreign_key(
        'fk_tenants_owner_id_users',
        'tenants',
        'users',
        ['owner_id'],
        ['uuid'],
        ondelete='SET NULL',
    )
    op.create_table('tenant_user_invitations',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('tenant_role_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=25), server_default='PENDING', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('requires_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_role_id'], ['tenant_roles.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_tenant_user_invitations_tenant_id', 'tenant_user_invitations', ['tenant_id'], unique=False)
    op.create_index('uq_tenant_user_invitations_pending_email', 'tenant_user_invitations', ['tenant_id', 'email'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('tenant_users',
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_support', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False, comment='Status'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_role_id', sa.UUID(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_role_id'], ['tenant_roles.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_tenant_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_owner_id_users', 'tenants', type_='foreignkey')
    op.drop_table('tenant_users')
    op.drop_index('uq_tenant_user_invitations_pending_email', table_name='tenant_user_invitations', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_tenant_user_invitations_tenant_id', table_name='tenant_user_invitations')
    op.drop_table('tenant_user_invitations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_roles_slug'), table_name='tenant_roles')
    op.drop_table('tenant_roles')
    op.drop_index('ix_tenant_api_keys_tenant', table_name='tenant_api_keys')
    op.drop_table('tenant_api_keys')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_deleted'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_phone_numbers_phone_number'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_dial_code'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_email_addresses_email'), table_name='email_addresses')
    op.drop_table('email_addresses')
    # ### end Alembic commands ###