"""synthesis

Revision ID: 4fd3772c2a94
Revises: 04a08a7f8e1b
Create Date: 2026-05-06 23:01:20.010886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4fd3772c2a94"
down_revision: Union[str, None] = "04a08a7f8e1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_rules",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column(
            "scope",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"mode":"ALL_DOCUMENTS","on_empty":"SKIPPED"}',
            nullable=False,
        ),
        sa.Column("knowledge_refs", postgresql.ARRAY(sa.UUID()), server_default="{}", nullable=False),
        sa.Column("current_compilation_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_compilation_id"],
            ["workflow_rule_compilations.uuid"],
            name="fk_workflow_rules_current_compilation",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index("ix_workflow_rules_tenant", "workflow_rules", ["tenant_id"], unique=False)
    op.create_index("ix_workflow_rules_workflow", "workflow_rules", ["workflow_id"], unique=False)
    op.create_table(
        "workflow_analysis_runs",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_case_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="RUNNING", nullable=False),
        sa.Column("trigger", sa.String(length=20), server_default="USER", nullable=False),
        sa.Column("triggered_by", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_by", sa.UUID(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("reviewer_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("critic_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("consensus_samples", sa.SmallInteger(), nullable=True),
        sa.Column("rules_total", sa.Integer(), nullable=True),
        sa.Column("rules_passed", sa.Integer(), nullable=True),
        sa.Column("rules_failed", sa.Integer(), nullable=True),
        sa.Column("rules_inconclusive", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["canceled_by"], ["users.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["triggered_by"], ["users.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workflow_case_id"], ["workflow_cases.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        "ix_workflow_analysis_runs_workflow_case_id", "workflow_analysis_runs", ["workflow_case_id"], unique=False
    )
    op.create_index(
        "ix_workflow_analysis_runs_workflow_case_status",
        "workflow_analysis_runs",
        ["workflow_case_id", "status"],
        unique=False,
    )
    op.create_table(
        "workflow_rule_compilations",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("artifact", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("compiled_with", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["rule_id"], ["workflow_rules.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("rule_id", "version", name="uq_workflow_rule_compilations_rule_version"),
    )
    op.create_index("ix_workflow_rule_compilations_rule", "workflow_rule_compilations", ["rule_id"], unique=False)
    op.create_table(
        "workflow_analysis_run_summaries",
        sa.Column("workflow_analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("signals_by_polarity", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("signals_by_severity", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("blocking_failures", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("degraded_rules", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_schema_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("synthesis_template_snapshot", sa.Text(), nullable=True),
        sa.Column("narrative_status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("narrative_error", sa.Text(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_analysis_run_id"], ["workflow_analysis_runs.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index("ix_run_summaries_tenant", "workflow_analysis_run_summaries", ["tenant_id"], unique=False)
    op.create_index(
        "uq_run_summaries_run", "workflow_analysis_run_summaries", ["workflow_analysis_run_id"], unique=True
    )
    op.create_table(
        "workflow_rule_results",
        sa.Column("workflow_analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("document_refs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("document_refs_hash", sa.String(length=64), nullable=False),
        sa.Column("rendered_prompt", sa.Text(), nullable=True),
        sa.Column("evaluation_metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["workflow_rules.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_analysis_run_id"], ["workflow_analysis_runs.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint(
            "workflow_analysis_run_id", "rule_id", "document_refs_hash", name="uq_workflow_rule_results_run_rule_refs"
        ),
    )
    op.create_index("ix_workflow_rule_results_rule", "workflow_rule_results", ["rule_id"], unique=False)
    op.create_index(
        "ix_workflow_rule_results_run", "workflow_rule_results", ["workflow_analysis_run_id"], unique=False
    )
    op.drop_index(op.f("ix_analysis_rule_results_case_id"), table_name="analysis_rule_results")
    op.drop_index(op.f("ix_analysis_rule_results_run_id"), table_name="analysis_rule_results")
    op.drop_table("analysis_rule_results")
    op.drop_index(op.f("ix_analysis_rules_workflow_id"), table_name="analysis_rules")
    op.drop_table("analysis_rules")
    op.drop_index(op.f("ix_analysis_runs_workflow_case_id"), table_name="analysis_runs")
    op.drop_index(op.f("ix_analysis_runs_workflow_case_status"), table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.add_column("kb_documents", sa.Column("slug", sa.String(length=100), nullable=False))
    op.create_index(
        "uq_kb_documents_tenant_slug_global",
        "kb_documents",
        ["tenant_id", "slug"],
        unique=True,
        postgresql_where=sa.text("workflow_id IS NULL"),
    )
    op.create_index(
        "uq_kb_documents_workflow_slug",
        "kb_documents",
        ["workflow_id", "slug"],
        unique=True,
        postgresql_where=sa.text("workflow_id IS NOT NULL"),
    )
    op.add_column("workflows", sa.Column("output_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("workflows", sa.Column("synthesis_template", sa.Text(), nullable=True))
    op.add_column("workflows", sa.Column("synthesis_enabled", sa.Boolean(), server_default="false", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "synthesis_enabled")
    op.drop_column("workflows", "synthesis_template")
    op.drop_column("workflows", "output_schema")
    op.drop_index(
        "uq_kb_documents_workflow_slug", table_name="kb_documents", postgresql_where=sa.text("workflow_id IS NOT NULL")
    )
    op.drop_index(
        "uq_kb_documents_tenant_slug_global",
        table_name="kb_documents",
        postgresql_where=sa.text("workflow_id IS NULL"),
    )
    op.drop_column("kb_documents", "slug")
    op.create_table(
        "analysis_runs",
        sa.Column("workflow_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("workflow_case_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'RUNNING'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.VARCHAR(length=20),
            server_default=sa.text("'USER'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("triggered_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("canceled_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("canceled_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("reviewer_model", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("critic_model", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("consensus_samples", sa.SMALLINT(), autoincrement=False, nullable=True),
        sa.Column("rules_total", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rules_passed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rules_failed", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("rules_inconclusive", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canceled_by"], ["users.uuid"], name="analysis_runs_canceled_by_fkey", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.uuid"], name="analysis_runs_tenant_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by"], ["users.uuid"], name="analysis_runs_triggered_by_fkey", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_case_id"],
            ["workflow_cases.uuid"],
            name="analysis_runs_workflow_case_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.uuid"], name="analysis_runs_workflow_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid", name="analysis_runs_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_analysis_runs_workflow_case_status"), "analysis_runs", ["workflow_case_id", "status"], unique=False
    )
    op.create_index(op.f("ix_analysis_runs_workflow_case_id"), "analysis_runs", ["workflow_case_id"], unique=False)
    op.create_table(
        "analysis_rules",
        sa.Column("workflow_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
        sa.Column(
            "kb_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "output_enabled", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False
        ),
        sa.Column("output_schema", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("parsed_checks", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column(
            "previous_parsed_checks", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("parser_version", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("parsed_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("parser_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("position", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.uuid"], name=op.f("analysis_rules_tenant_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.uuid"], name=op.f("analysis_rules_workflow_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("analysis_rules_pkey")),
    )
    op.create_index(op.f("ix_analysis_rules_workflow_id"), "analysis_rules", ["workflow_id"], unique=False)
    op.create_table(
        "analysis_rule_results",
        sa.Column("analysis_run_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("workflow_case_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("analysis_rule_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_passed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("reasoning", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("structured_output", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("rendered_prompt", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "document_refs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "preliminary_checks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "consensus",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("critic_feedback", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("critic_iterations", sa.INTEGER(), server_default=sa.text("0"), autoincrement=False, nullable=False),
        sa.Column(
            "verification_warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "unresolved_tokens",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_rule_id"],
            ["analysis_rules.uuid"],
            name=op.f("analysis_rule_results_analysis_rule_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.uuid"],
            name=op.f("analysis_rule_results_analysis_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.uuid"], name=op.f("analysis_rule_results_tenant_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workflow_case_id"],
            ["workflow_cases.uuid"],
            name=op.f("analysis_rule_results_workflow_case_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("analysis_rule_results_pkey")),
    )
    op.create_index(
        op.f("ix_analysis_rule_results_run_id"), "analysis_rule_results", ["analysis_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_analysis_rule_results_case_id"), "analysis_rule_results", ["workflow_case_id"], unique=False
    )
    op.drop_index("ix_workflow_rule_results_run", table_name="workflow_rule_results")
    op.drop_index("ix_workflow_rule_results_rule", table_name="workflow_rule_results")
    op.drop_table("workflow_rule_results")
    op.drop_index("uq_run_summaries_run", table_name="workflow_analysis_run_summaries")
    op.drop_index("ix_run_summaries_tenant", table_name="workflow_analysis_run_summaries")
    op.drop_table("workflow_analysis_run_summaries")
    op.drop_index("ix_workflow_rule_compilations_rule", table_name="workflow_rule_compilations")
    op.drop_table("workflow_rule_compilations")
    op.drop_index("ix_workflow_analysis_runs_workflow_case_status", table_name="workflow_analysis_runs")
    op.drop_index("ix_workflow_analysis_runs_workflow_case_id", table_name="workflow_analysis_runs")
    op.drop_table("workflow_analysis_runs")
    op.drop_index("ix_workflow_rules_workflow", table_name="workflow_rules")
    op.drop_index("ix_workflow_rules_tenant", table_name="workflow_rules")
    op.drop_table("workflow_rules")
    # ### end Alembic commands ###
