"""add_doctype_sample_fields

Revision ID: 04a08a7f8e1b
Revises: a1b2c3d4e5f6
Create Date: 2026-05-04 08:10:10.425508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04a08a7f8e1b"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_types", sa.Column("sample_file_text", sa.Text(), nullable=True))
    op.create_foreign_key(None, "tenants", "users", ["owner_id"], ["uuid"], ondelete="SET NULL", use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tenants", type_="foreignkey")
    op.drop_column("document_types", "sample_file_text")
    # ### end Alembic commands ###
