"""squash re-arch schema

Revision ID: 218667cf7839
Revises: f6b7c8d9e0a1
Create Date: 2026-06-16 17:23:00.919215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '218667cf7839'
down_revision: Union[str, None] = 'f6b7c8d9e0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('workflow_id', name='uq_pipelines_workflow_id')
    )
    op.create_index(op.f('ix_pipelines_workflow_id'), 'pipelines', ['workflow_id'], unique=False)
    op.create_table('classifiers',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_classifiers_tenant_slug')
    )
    op.create_index(op.f('ix_classifiers_slug'), 'classifiers', ['slug'], unique=False)
    op.create_table('eval_datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pipeline_slug', sa.String(length=120), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('human_tasks',
    sa.Column('task_key', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('assignee_mode', sa.String(length=30), server_default='internal_queue', nullable=False),
    sa.Column('audience', sa.String(length=60), nullable=True),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_run_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('claimed_by', sa.String(length=80), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('task_key', name='uq_human_tasks_task_key')
    )
    op.create_index('ix_human_tasks_case', 'human_tasks', ['case_id'], unique=False)
    op.create_index('ix_human_tasks_stage_status', 'human_tasks', ['stage', 'status'], unique=False, postgresql_where=sa.text('stage IS NOT NULL'))
    op.create_index('ix_human_tasks_tenant_status', 'human_tasks', ['tenant_id', 'status'], unique=False)
    op.create_table('pipeline_versions',
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('pipeline_id', 'version', name='uq_pipeline_versions_pipeline_version')
    )
    op.create_index(op.f('ix_pipeline_versions_pipeline_id'), 'pipeline_versions', ['pipeline_id'], unique=False)
    op.create_table('tenant_api_keys',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('key_hash', name='uq_tenant_api_keys_key_hash')
    )
    op.create_index('ix_tenant_api_keys_tenant', 'tenant_api_keys', ['tenant_id'], unique=False)
    op.create_table('eval_cases',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('input_ref', sa.String(length=512), nullable=False),
    sa.Column('expected', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['eval_datasets.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_eval_cases_dataset_id'), 'eval_cases', ['dataset_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['eval_datasets.uuid'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_eval_runs_dataset_id'), 'eval_runs', ['dataset_id'], unique=False)
    op.create_table('staff_users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_id', name='uq_staff_users_user_id')
    )
    op.create_table('tool_definitions',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=20), server_default='HTTP', nullable=False),
    sa.Column('connection_account_id', sa.UUID(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_account_id'], ['connection_accounts.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('workflow_id', 'name', name='uq_tool_definitions_workflow_name')
    )
    op.create_index(op.f('ix_tool_definitions_connection_account_id'), 'tool_definitions', ['connection_account_id'], unique=False)
    op.create_index(op.f('ix_tool_definitions_workflow_id'), 'tool_definitions', ['workflow_id'], unique=False)
    op.create_table('workflow_destinations',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), server_default='WEBHOOK', nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('secret', sa.String(length=512), nullable=True),
    sa.Column('subscribed_events', postgresql.JSONB(astext_type=sa.Text()), server_default='["document.extracted", "document.failed"]', nullable=False),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connection_accounts.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_workflow_destinations_tenant_created', 'workflow_destinations', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_workflow_destinations_workflow', 'workflow_destinations', ['workflow_id'], unique=False)
    op.create_table('workflow_sources',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), server_default='WEBHOOK', nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('route_token', sa.String(length=120), nullable=False),
    sa.Column('auth_mode', sa.String(length=20), server_default='api_key', nullable=False),
    sa.Column('secret', sa.String(length=512), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connection_accounts.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('route_token', name='uq_workflow_sources_route_token')
    )
    op.create_index('ix_workflow_sources_tenant_created', 'workflow_sources', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_workflow_sources_workflow', 'workflow_sources', ['workflow_id'], unique=False)
    op.create_table('case_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['workflow_cases.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index('ix_case_events_case_created', 'case_events', ['case_id', 'created_at'], unique=False)
    op.create_index('ix_case_events_tenant', 'case_events', ['tenant_id'], unique=False)
    op.create_index('ix_case_events_tenant_type_created', 'case_events', ['tenant_id', 'type', 'created_at'], unique=False)
    op.create_table('document_type_versions',
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_rules', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('document_type_id', 'version', name='uq_document_type_versions_doctype_version')
    )
    op.create_index(op.f('ix_document_type_versions_document_type_id'), 'document_type_versions', ['document_type_id'], unique=False)
    op.create_table('source_deliveries',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='received', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['workflow_sources.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('source_id', 'idempotency_key', name='uq_source_deliveries_source_key')
    )
    op.create_index('ix_source_deliveries_source', 'source_deliveries', ['source_id'], unique=False)
    op.create_table('staff_access_events',
    sa.Column('staff_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=80), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['staff_users.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_staff_access_events_created', 'staff_access_events', ['created_at'], unique=False)
    op.create_index('ix_staff_access_events_staff_user', 'staff_access_events', ['staff_user_id'], unique=False)
    op.create_index('ix_staff_access_events_tenant', 'staff_access_events', ['tenant_id'], unique=False)
    op.create_table('tool_call_snapshots',
    sa.Column('tool_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_definitions.uuid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('ix_tool_call_snapshots_case', 'tool_call_snapshots', ['case_id', 'created_at'], unique=False)
    op.create_index('ix_tool_call_snapshots_tool', 'tool_call_snapshots', ['tool_id', 'created_at'], unique=False)
    op.create_table('workflow_processing_jobs',
    sa.Column('temporal_workflow_id', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('trigger', sa.String(length=20), server_default='USER', nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('workflow_case_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('last_seq', sa.Integer(), server_default='0', nullable=False),
    sa.Column('extracted_text', sa.String(length=512), nullable=True),
    sa.Column('classified_pages', sa.String(length=512), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.uuid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['documents.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_case_id'], ['workflow_cases.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('temporal_workflow_id')
    )
    op.create_index('ix_workflow_processing_jobs_status', 'workflow_processing_jobs', ['status'], unique=False)
    op.drop_table('validation_rules')
    op.add_column('document_types', sa.Column('current_version', sa.Integer(), nullable=True))
    op.add_column('workflow_analysis_run_summaries', sa.Column('output_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_cases', sa.Column('external_ref', sa.String(length=255), nullable=True))
    op.add_column('workflow_cases', sa.Column('pipeline_id', sa.UUID(), nullable=True))
    op.add_column('workflow_cases', sa.Column('pipeline_version_id', sa.UUID(), nullable=True))
    op.add_column('workflow_cases', sa.Column('parent_case_id', sa.UUID(), nullable=True))
    op.add_column('workflow_cases', sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_cases', sa.Column('completeness', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('workflow_cases', 'status',
               existing_type=sa.String(length=20),
               server_default='RECEIVING',
               existing_nullable=False)
    op.create_index('ix_workflow_cases_parent', 'workflow_cases', ['parent_case_id'], unique=False)
    op.create_unique_constraint('uq_workflow_cases_workflow_external_ref', 'workflow_cases', ['workflow_id', 'external_ref'])
    op.create_foreign_key(None, 'workflow_cases', 'workflow_cases', ['parent_case_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflow_cases', 'pipeline_versions', ['pipeline_version_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflow_cases', 'pipelines', ['pipeline_id'], ['uuid'], ondelete='SET NULL')
    op.add_column('workflow_documents', sa.Column('document_type_version', sa.Integer(), nullable=True))
    op.add_column('workflow_documents', sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_documents', sa.Column('needs_clarification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_documents', sa.Column('extract_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_documents', sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_documents', sa.Column('verification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_documents', sa.Column('parent_document_id', sa.UUID(), nullable=True))
    op.add_column('workflow_documents', sa.Column('processing_job_id', sa.UUID(), nullable=True))
    op.add_column('workflow_documents', sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_documents', sa.Column('output_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('workflow_documents', 'source',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'SINGLE'::character varying"))
    op.drop_constraint(op.f('workflow_documents_document_set_id_fkey'), 'workflow_documents', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_documents', 'workflow_processing_jobs', ['processing_job_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflow_documents', 'workflow_documents', ['parent_document_id'], ['uuid'], ondelete='SET NULL')
    op.drop_column('workflow_documents', 'document_set_id')
    op.add_column('workflow_events', sa.Column('idempotency_key', sa.String(length=255), nullable=False))
    op.alter_column('workflow_events', 'processing_job_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.UUID(),
               postgresql_using='processing_job_id::uuid',
               nullable=True)
    op.drop_constraint(op.f('uq_workflow_events_doc_type_job'), 'workflow_events', type_='unique')
    op.create_unique_constraint('uq_workflow_events_doc_type_job', 'workflow_events', ['document_id', 'event_type', 'idempotency_key', 'destination_id'])
    op.drop_constraint(op.f('workflow_events_document_set_id_fkey'), 'workflow_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_workflow_events_destination'), 'workflow_events', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_events', 'workflow_processing_jobs', ['processing_job_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workflow_events', 'workflow_destinations', ['destination_id'], ['uuid'], ondelete='SET NULL')
    op.drop_column('workflow_events', 'document_set_id')
    op.drop_index(op.f('ix_workflow_document_sets_status'), table_name='workflow_document_sets')
    op.drop_table('workflow_document_sets')
    op.drop_index(op.f('ix_webhook_destinations_tenant_created'), table_name='webhook_destinations')
    op.drop_index(op.f('ix_webhook_destinations_workflow'), table_name='webhook_destinations')
    op.drop_table('webhook_destinations')
    op.add_column('workflow_rules', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('workflow_rules', sa.Column('when_expr', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_workflow_rules_workflow_slug', 'workflow_rules', ['workflow_id', 'slug'])
    op.create_foreign_key('fk_workflow_rules_current_compilation', 'workflow_rules', 'workflow_rule_compilations', ['current_compilation_id'], ['uuid'], ondelete='SET NULL', use_alter=True)
    op.add_column('workflows', sa.Column('pipeline_id', sa.UUID(), nullable=True))
    op.add_column('workflows', sa.Column('synthesis_uses_documents', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('workflows', sa.Column('case_noun', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_workflows_pipeline_id'), 'workflows', ['pipeline_id'], unique=False)
    op.create_foreign_key(None, 'workflows', 'pipelines', ['pipeline_id'], ['uuid'], ondelete='SET NULL')
    op.drop_column('workflows', 'workflow_type')
    op.drop_column('workflows', 'doc_type_catalog')
    op.drop_column('workflows', 'default_schemas')
    op.drop_column('workflows', 'per_doc_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('per_doc_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('default_schemas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('doc_type_catalog', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('workflow_type', sa.VARCHAR(length=20), server_default=sa.text("'STANDARD'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint('workflows_pipeline_id_fkey', 'workflows', type_='foreignkey')
    op.drop_index(op.f('ix_workflows_pipeline_id'), table_name='workflows')
    op.drop_column('workflows', 'case_noun')
    op.drop_column('workflows', 'synthesis_uses_documents')
    op.drop_column('workflows', 'pipeline_id')
    op.drop_constraint('fk_workflow_rules_current_compilation', 'workflow_rules', type_='foreignkey')
    op.drop_constraint('uq_workflow_rules_workflow_slug', 'workflow_rules', type_='unique')
    op.drop_column('workflow_rules', 'when_expr')
    op.drop_column('workflow_rules', 'slug')
    op.add_column('workflow_events', sa.Column('document_set_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('workflow_events_processing_job_id_fkey', 'workflow_events', type_='foreignkey')
    op.drop_constraint('workflow_events_destination_id_fkey', 'workflow_events', type_='foreignkey')
    op.drop_constraint('uq_workflow_events_doc_type_job', 'workflow_events', type_='unique')
    op.create_unique_constraint(op.f('uq_workflow_events_doc_type_job'), 'workflow_events', ['document_id', 'event_type', 'processing_job_id', 'destination_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('workflow_events', 'processing_job_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=255),
               postgresql_using='processing_job_id::text',
               nullable=False)
    op.drop_column('workflow_events', 'idempotency_key')
    op.add_column('workflow_documents', sa.Column('document_set_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('workflow_documents_processing_job_id_fkey', 'workflow_documents', type_='foreignkey')
    op.drop_constraint('workflow_documents_parent_document_id_fkey', 'workflow_documents', type_='foreignkey')
    op.alter_column('workflow_documents', 'source',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'SINGLE'::character varying"))
    op.drop_column('workflow_documents', 'output_provenance')
    op.drop_column('workflow_documents', 'output')
    op.drop_column('workflow_documents', 'processing_job_id')
    op.drop_column('workflow_documents', 'parent_document_id')
    op.drop_column('workflow_documents', 'verification')
    op.drop_column('workflow_documents', 'signals')
    op.drop_column('workflow_documents', 'extract_confidence')
    op.drop_column('workflow_documents', 'needs_clarification')
    op.drop_column('workflow_documents', 'field_confidence')
    op.drop_column('workflow_documents', 'document_type_version')
    op.alter_column('workflow_cases', 'status',
               existing_type=sa.String(length=20),
               server_default='DRAFT',
               existing_nullable=False)
    op.drop_constraint('workflow_cases_parent_case_id_fkey', 'workflow_cases', type_='foreignkey')
    op.drop_constraint('workflow_cases_pipeline_version_id_fkey', 'workflow_cases', type_='foreignkey')
    op.drop_constraint('workflow_cases_pipeline_id_fkey', 'workflow_cases', type_='foreignkey')
    op.drop_constraint('uq_workflow_cases_workflow_external_ref', 'workflow_cases', type_='unique')
    op.drop_index('ix_workflow_cases_parent', table_name='workflow_cases')
    op.drop_column('workflow_cases', 'completeness')
    op.drop_column('workflow_cases', 'ready_at')
    op.drop_column('workflow_cases', 'parent_case_id')
    op.drop_column('workflow_cases', 'pipeline_version_id')
    op.drop_column('workflow_cases', 'pipeline_id')
    op.drop_column('workflow_cases', 'external_ref')
    op.drop_column('workflow_analysis_run_summaries', 'output_provenance')
    op.drop_column('document_types', 'current_version')
    op.create_table('webhook_destinations',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('subscribed_events', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'["document.extracted", "document.failed"]\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('api_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], name=op.f('webhook_destinations_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.uuid'], name=op.f('webhook_destinations_workflow_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('webhook_destinations_pkey'))
    )
    op.create_index(op.f('ix_webhook_destinations_workflow'), 'webhook_destinations', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_webhook_destinations_tenant_created'), 'webhook_destinations', ['tenant_id', 'created_at'], unique=False)
    op.create_table('workflow_document_sets',
    sa.Column('processing_job_id', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('trigger', sa.VARCHAR(length=20), server_default=sa.text("'USER'::character varying"), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workflow_case_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_seq', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('extracted_text', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('classified_pages', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.uuid'], name=op.f('workflow_document_sets_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['documents.uuid'], name=op.f('workflow_document_sets_file_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], name=op.f('workflow_document_sets_tenant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_case_id'], ['workflow_cases.uuid'], name=op.f('workflow_document_sets_workflow_case_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.uuid'], name=op.f('workflow_document_sets_workflow_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('workflow_document_sets_pkey')),
    sa.UniqueConstraint('processing_job_id', name=op.f('workflow_document_sets_processing_job_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_workflow_document_sets_status'), 'workflow_document_sets', ['status'], unique=False)
    op.create_table('validation_rules',
    sa.Column('document_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.uuid'], name=op.f('validation_rules_document_type_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.uuid'], name=op.f('validation_rules_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('validation_rules_pkey'))
    )
    op.create_foreign_key(op.f('fk_workflow_events_destination'), 'workflow_events', 'webhook_destinations', ['destination_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(op.f('workflow_events_document_set_id_fkey'), 'workflow_events', 'workflow_document_sets', ['document_set_id'], ['uuid'], ondelete='SET NULL')
    op.create_foreign_key(op.f('workflow_documents_document_set_id_fkey'), 'workflow_documents', 'workflow_document_sets', ['document_set_id'], ['uuid'], ondelete='SET NULL')
    op.drop_index('ix_workflow_processing_jobs_status', table_name='workflow_processing_jobs')
    op.drop_table('workflow_processing_jobs')
    op.drop_index('ix_tool_call_snapshots_tool', table_name='tool_call_snapshots')
    op.drop_index('ix_tool_call_snapshots_case', table_name='tool_call_snapshots')
    op.drop_table('tool_call_snapshots')
    op.drop_index('ix_staff_access_events_tenant', table_name='staff_access_events')
    op.drop_index('ix_staff_access_events_staff_user', table_name='staff_access_events')
    op.drop_index('ix_staff_access_events_created', table_name='staff_access_events')
    op.drop_table('staff_access_events')
    op.drop_index('ix_source_deliveries_source', table_name='source_deliveries')
    op.drop_table('source_deliveries')
    op.drop_index(op.f('ix_document_type_versions_document_type_id'), table_name='document_type_versions')
    op.drop_table('document_type_versions')
    op.drop_index('ix_case_events_tenant_type_created', table_name='case_events')
    op.drop_index('ix_case_events_tenant', table_name='case_events')
    op.drop_index('ix_case_events_case_created', table_name='case_events')
    op.drop_table('case_events')
    op.drop_index('ix_workflow_sources_workflow', table_name='workflow_sources')
    op.drop_index('ix_workflow_sources_tenant_created', table_name='workflow_sources')
    op.drop_table('workflow_sources')
    op.drop_index('ix_workflow_destinations_workflow', table_name='workflow_destinations')
    op.drop_index('ix_workflow_destinations_tenant_created', table_name='workflow_destinations')
    op.drop_table('workflow_destinations')
    op.drop_index(op.f('ix_tool_definitions_workflow_id'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_connection_account_id'), table_name='tool_definitions')
    op.drop_table('tool_definitions')
    op.drop_table('staff_users')
    op.drop_index(op.f('ix_eval_runs_dataset_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_eval_cases_dataset_id'), table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_index('ix_tenant_api_keys_tenant', table_name='tenant_api_keys')
    op.drop_table('tenant_api_keys')
    op.drop_index(op.f('ix_pipeline_versions_pipeline_id'), table_name='pipeline_versions')
    op.drop_table('pipeline_versions')
    op.drop_index('ix_human_tasks_tenant_status', table_name='human_tasks')
    op.drop_index('ix_human_tasks_stage_status', table_name='human_tasks', postgresql_where=sa.text('stage IS NOT NULL'))
    op.drop_index('ix_human_tasks_case', table_name='human_tasks')
    op.drop_table('human_tasks')
    op.drop_table('eval_datasets')
    op.drop_index(op.f('ix_classifiers_slug'), table_name='classifiers')
    op.drop_table('classifiers')
    op.drop_index(op.f('ix_pipelines_workflow_id'), table_name='pipelines')
    op.drop_table('pipelines')
    # ### end Alembic commands ###