"""initial

Revision ID: 55c61ec5b69b
Revises:
Create Date: 2026-05-03 08:45:05.263402

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "55c61ec5b69b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "email_addresses",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_email_addresses_email"), "email_addresses", ["email"], unique=True)
    op.create_table(
        "industries",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "phone_numbers",
        sa.Column("iso_code", sa.String(length=3), nullable=False),
        sa.Column("dial_code", sa.SmallInteger(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("dial_code", "phone_number", name="uq_phone_numbers_dial_code_phone_number"),
    )
    op.create_index(op.f("ix_phone_numbers_dial_code"), "phone_numbers", ["dial_code"], unique=False)
    op.create_index(op.f("ix_phone_numbers_phone_number"), "phone_numbers", ["phone_number"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=25), nullable=False, comment="Status"),
        sa.Column("time_zone", sa.String(length=50), nullable=False),
        sa.Column("country_code", sa.String(length=25), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("view_workspace", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("webhook_signature_key", sa.String(length=255), nullable=True),
        sa.Column(
            "processing_case_types", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.uuid"], ondelete="SET NULL", use_alter=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_tenants_is_deleted"), "tenants", ["is_deleted"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "documents",
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime", sa.String(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("s3_key", sa.String(length=512), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "tenant_industries",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("industry_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["industry_id"], ["industries.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("tenant_id", "industry_id"),
    )
    op.create_table(
        "tenant_roles",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=25), nullable=False, comment="Status"),
        sa.Column("icon_url", sa.String(length=255), nullable=True),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_tenant_role_tenant_slug"),
    )
    op.create_index(op.f("ix_tenant_roles_slug"), "tenant_roles", ["slug"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=True, comment="Hashed password"),
        sa.Column("email_address_id", sa.UUID(), nullable=True),
        sa.Column("phone_number_id", sa.UUID(), nullable=True),
        sa.Column("current_tenant_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("first_name", sa.String(length=150), nullable=True),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_tenant_id"],
            ["tenants.uuid"],
            name="fk_current_tenant_id",
            ondelete="SET NULL",
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(["email_address_id"], ["email_addresses.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["phone_number_id"], ["phone_numbers.uuid"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("email_address_id", name="uq_users_email_address_id"),
        sa.UniqueConstraint("phone_number_id", name="uq_users_phone_number_id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "document_pages",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False, comment="1-indexed page number"),
        sa.Column("page_file", sa.Text(), nullable=True, comment="S3 key for the page image"),
        sa.Column("cleaned_page_file", sa.Text(), nullable=True, comment="S3 key for the cleaned page image"),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("document_id", "page_number"),
    )
    op.create_table(
        "tenant_users",
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("is_support", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=25), nullable=False, comment="Status"),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tenant_role_id", sa.UUID(), nullable=True),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("photo", sa.String(length=500), nullable=True),
        sa.Column("first_name", sa.String(length=150), nullable=True),
        sa.Column("last_name", sa.String(length=150), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_role_id"], ["tenant_roles.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("user_id", "tenant_id", name="uq_tenant_user_id"),
    )
    op.create_table(
        "workflows",
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("industry_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("workflow_type", sa.String(length=20), server_default="STANDARD", nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("generic_prompt", sa.Text(), nullable=True),
        sa.Column("extraction_prompt", sa.Text(), nullable=True),
        sa.Column("prompt_overrides", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("doc_type_catalog", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("default_schemas", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("selected_doc_types", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("per_doc_schema", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("kb_document_ids", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("per_doc_kb_ids", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("structuring_model", sa.String(length=100), nullable=True),
        sa.Column("llm_model", sa.String(length=100), nullable=True),
        sa.Column("analysis_reviewer_model", sa.String(length=100), nullable=True),
        sa.Column("analysis_critic_model", sa.String(length=100), nullable=True),
        sa.Column("analysis_consensus_samples", sa.Integer(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("is_archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_main", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["industry_id"], ["industries.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        "ix_workflows_tenant_archived_created", "workflows", ["tenant_id", "is_archived", "created_at"], unique=False
    )
    op.create_table(
        "analysis_rules",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("kb_ids", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("output_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("output_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parsed_checks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("previous_parsed_checks", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("parser_version", sa.String(length=50), nullable=True),
        sa.Column("parsed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parser_error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index("ix_analysis_rules_workflow_id", "analysis_rules", ["workflow_id"], unique=False)
    op.create_table(
        "document_types",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_shareable", sa.Boolean(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation_rules", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("sample_file_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["sample_file_id"], ["documents.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "kb_documents",
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime", sa.String(length=100), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("workflow_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=25), server_default="vectorizing", nullable=False),
        sa.Column("chunk_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["documents.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workflow_id"], ["workflows.uuid"], name="fk_kb_documents_workflow_id", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index("ix_kb_documents_workflow_id", "kb_documents", ["workflow_id"], unique=False)
    op.create_table(
        "workflow_cases",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="DRAFT", nullable=False),
        sa.Column("last_ocr_provider", sa.String(length=20), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index("ix_workflow_cases_workflow_id", "workflow_cases", ["workflow_id"], unique=False)
    op.create_table(
        "analysis_runs",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_case_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="RUNNING", nullable=False),
        sa.Column("trigger", sa.String(length=20), server_default="USER", nullable=False),
        sa.Column("triggered_by", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("canceled_by", sa.UUID(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("reviewer_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("critic_model", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("consensus_samples", sa.SmallInteger(), nullable=True),
        sa.Column("rules_total", sa.Integer(), nullable=True),
        sa.Column("rules_passed", sa.Integer(), nullable=True),
        sa.Column("rules_failed", sa.Integer(), nullable=True),
        sa.Column("rules_inconclusive", sa.Integer(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["canceled_by"], ["users.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["triggered_by"], ["users.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workflow_case_id"], ["workflow_cases.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index("ix_analysis_runs_workflow_case_id", "analysis_runs", ["workflow_case_id"], unique=False)
    op.create_index(
        "ix_analysis_runs_workflow_case_status", "analysis_runs", ["workflow_case_id", "status"], unique=False
    )
    op.create_table(
        "kb_embeddings",
        sa.Column("kb_document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["kb_document_id"], ["kb_documents.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("kb_document_id", "chunk_index"),
    )
    op.create_table(
        "validation_rules",
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_type_id"], ["document_types.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "workflow_document_sets",
        sa.Column("processing_job_id", sa.String(length=120), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("trigger", sa.String(length=20), server_default="USER", nullable=False),
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_case_id", sa.UUID(), nullable=True),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="PENDING", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("result_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("current_step", sa.String(length=50), nullable=True),
        sa.Column("last_seq", sa.Integer(), server_default="0", nullable=False),
        sa.Column("extracted_text", sa.String(length=512), nullable=True),
        sa.Column("classified_pages", sa.String(length=512), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["file_id"], ["documents.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_case_id"], ["workflow_cases.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("processing_job_id"),
    )
    op.create_index("ix_workflow_document_sets_status", "workflow_document_sets", ["status"], unique=False)
    op.create_table(
        "workflow_document_types",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_type_id"], ["document_types.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("workflow_id", "document_type_id"),
    )
    op.create_table(
        "analysis_rule_results",
        sa.Column("analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("workflow_case_id", sa.UUID(), nullable=False),
        sa.Column("analysis_rule_id", sa.UUID(), nullable=False),
        sa.Column("is_passed", sa.Boolean(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("structured_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rendered_prompt", sa.Text(), nullable=True),
        sa.Column("document_refs", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("preliminary_checks", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("consensus", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("critic_feedback", sa.Text(), nullable=True),
        sa.Column("critic_iterations", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "verification_warnings", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("unresolved_tokens", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analysis_rule_id"], ["analysis_rules.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_case_id"], ["workflow_cases.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index("ix_analysis_rule_results_case_id", "analysis_rule_results", ["workflow_case_id"], unique=False)
    op.create_index("ix_analysis_rule_results_run_id", "analysis_rule_results", ["analysis_run_id"], unique=False)
    op.create_table(
        "workflow_documents",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_case_id", sa.UUID(), nullable=True),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("document_type_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=25), server_default="EMPTY", nullable=False),
        sa.Column("source", sa.String(length=10), server_default="SINGLE", nullable=False),
        sa.Column("extraction", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("validation", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("mapped_extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("extraction_pages", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("extraction_metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("document_set_id", sa.UUID(), nullable=True),
        sa.Column("document_index", sa.Integer(), nullable=True),
        sa.Column("page_range", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("processing_status", sa.String(length=20), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_set_id"], ["workflow_document_sets.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["document_type_id"], ["document_types.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_case_id"], ["workflow_cases.uuid"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index("ix_wf_docs_tenant_workflow", "workflow_documents", ["tenant_id", "workflow_id"], unique=False)
    op.create_index("ix_wf_docs_workflow_status", "workflow_documents", ["workflow_id", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_wf_docs_workflow_status", table_name="workflow_documents")
    op.drop_index("ix_wf_docs_tenant_workflow", table_name="workflow_documents")
    op.drop_table("workflow_documents")
    op.drop_index("ix_analysis_rule_results_run_id", table_name="analysis_rule_results")
    op.drop_index("ix_analysis_rule_results_case_id", table_name="analysis_rule_results")
    op.drop_table("analysis_rule_results")
    op.drop_table("workflow_document_types")
    op.drop_index("ix_workflow_document_sets_status", table_name="workflow_document_sets")
    op.drop_table("workflow_document_sets")
    op.drop_table("validation_rules")
    op.drop_table("kb_embeddings")
    op.drop_index("ix_analysis_runs_workflow_case_status", table_name="analysis_runs")
    op.drop_index("ix_analysis_runs_workflow_case_id", table_name="analysis_runs")
    op.drop_table("analysis_runs")
    op.drop_index("ix_workflow_cases_workflow_id", table_name="workflow_cases")
    op.drop_table("workflow_cases")
    op.drop_index("ix_kb_documents_workflow_id", table_name="kb_documents")
    op.drop_table("kb_documents")
    op.drop_table("document_types")
    op.drop_index("ix_analysis_rules_workflow_id", table_name="analysis_rules")
    op.drop_table("analysis_rules")
    op.drop_index("ix_workflows_tenant_archived_created", table_name="workflows")
    op.drop_table("workflows")
    op.drop_table("tenant_users")
    op.drop_table("document_pages")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenant_roles_slug"), table_name="tenant_roles")
    op.drop_table("tenant_roles")
    op.drop_table("tenant_industries")
    op.drop_table("documents")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_is_deleted"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_phone_numbers_phone_number"), table_name="phone_numbers")
    op.drop_index(op.f("ix_phone_numbers_dial_code"), table_name="phone_numbers")
    op.drop_table("phone_numbers")
    op.drop_table("industries")
    op.drop_index(op.f("ix_email_addresses_email"), table_name="email_addresses")
    op.drop_table("email_addresses")
    # ### end Alembic commands ###
