import type { Document } from "@/src/domain/entities/document";
import { DocumentStatus } from "@/src/domain/entities/document";
import type { ErrorFeeback } from "@/src/domain/errors/error-feeback";
import type { DocumentRepository } from "@/src/domain/repositories/document";
import type {
  DocumentResponse,
  DocumentListResponse,
} from "@/src/domain/responses/document";
import type TaskResultResponse from "@/src/domain/responses/task-result";
import { successTask } from "@/src/domain/responses/task-result";
import type { DocumentType } from "@/src/domain/entities/doctype";

// Mock documents with realistic data for each workflow
const mockDocuments: Document[] = [
  // ATC CV Processing Workflow (ws-atc-processing)
  {
    uuid: "doc-fp-001",
    name: "CV_Education_Roberto_Gonzalez_20240120.pdf",
    identifier: "EDU-RG-20240120",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-20T08:30:00Z",
    confirmedAt: "2024-01-20T09:15:00Z",
    fileSize: 156789,
    mimeType: "application/pdf",
    workflowUuid: "ws-atc-processing",
    doctype: {
      uuid: "dt-flight-plan",
      name: "CV Education Verification",
      description: "Educational background verification document",
      workflowCount: 1,
      fieldsCount: 12,
      checksCount: 3,
      sampleDocument: "/docs/cv_roberto.pdf",
    },
    tags: ["Bachelor's Degree", "Verified"],
    extractedData: {
      pdfUrl: "/docs/cv_roberto.pdf",
      extractedAt: "2024-01-20T08:35:00Z",
      processingTime: 3200,
      fields: [
        {
          fieldUuid: "field-001",
          fieldName: "Full Name",
          fieldType: "text",
          value: "Roberto Eduardo González Villalpando",
          confidence: 0.98,
          validated: true,
        },
        {
          fieldUuid: "field-002",
          fieldName: "Email",
          fieldType: "email",
          value: "betolalomx@gmail.com",
          confidence: 0.99,
          validated: true,
        },
        {
          fieldUuid: "field-003",
          fieldName: "Phone Number",
          fieldType: "phone",
          value: "5548223426",
          confidence: 0.95,
          validated: true,
        },
        {
          fieldUuid: "field-004",
          fieldName: "Location",
          fieldType: "location",
          value:
            "Aguascalientes, Ags. | Querétaro, Qro. | Ciudad de México, CDMX",
          confidence: 0.92,
          validated: true,
        },
        {
          fieldUuid: "field-005",
          fieldName: "Professional Summary",
          fieldType: "textarea",
          value:
            "Profesional con más de 24 años de experiencia en Retail. he ocupado cargos gerenciales y directivos, desarrollando expertise en operaciones, visual merchandising, marketing, capacitación, ventas y coaching.",
          confidence: 0.88,
          validated: true,
        },
        {
          fieldUuid: "field-006",
          fieldName: "Work Experience",
          fieldType: "textarea",
          value: "1 Item",
          confidence: 0.9,
          validated: false,
        },
        {
          fieldUuid: "field-007",
          fieldName: "Education",
          fieldType: "textarea",
          value: "1 Item",
          confidence: 0.85,
          validated: false,
        },
        {
          fieldUuid: "field-008",
          fieldName: "Skills",
          fieldType: "multiselect",
          value: [
            "Pensamiento estratégico y toma de decisiones",
            "Coaching, mentoring y desarrollo de talento",
            "Gestión del cambio y adaptación en entornos dinámicos",
          ],
          confidence: 0.93,
          validated: true,
        },
      ],
    },
  },
  {
    uuid: "doc-fp-002",
    name: "CV_Education_Ana_Martinez_20240119.pdf",
    identifier: "EDU-AM-20240119",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-19T14:20:00Z",
    fileSize: 145234,
    mimeType: "application/pdf",
    workflowUuid: "ws-atc-processing",
    doctype: {
      uuid: "dt-flight-plan",
      name: "CV Education Verification",
      description: "Educational background verification document",
      workflowCount: 1,
      fieldsCount: 12,
      checksCount: 3,
      sampleDocument: "/docs/cv_roberto.pdf",
    },
    tags: ["Master's Degree", "Pending"],
    extractedData: {
      pdfUrl: "/docs/cv_roberto.pdf",
      extractedAt: "2024-01-19T14:25:00Z",
      processingTime: 2800,
      fields: [
        {
          fieldUuid: "field-001",
          fieldName: "Full Name",
          fieldType: "text",
          value: "Ana María Martínez López",
          confidence: 0.97,
          validated: false,
        },
        {
          fieldUuid: "field-002",
          fieldName: "Email",
          fieldType: "email",
          value: "ana.martinez@example.com",
          confidence: 0.96,
          validated: false,
        },
        {
          fieldUuid: "field-003",
          fieldName: "Phone Number",
          fieldType: "phone",
          value: "5512345678",
          confidence: 0.89,
          validated: false,
        },
        {
          fieldUuid: "field-004",
          fieldName: "Location",
          fieldType: "location",
          value: "Ciudad de México, CDMX",
          confidence: 0.94,
          validated: false,
        },
      ],
    },
  },
  {
    uuid: "doc-pl-001",
    name: "CV_Employment_Roberto_Gonzalez_20240118.pdf",
    identifier: "EMP-RG-2024001",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-18T10:45:00Z",
    confirmedAt: "2024-01-18T15:30:00Z",
    fileSize: 234567,
    mimeType: "application/pdf",
    workflowUuid: "ws-atc-processing",
    doctype: {
      uuid: "dt-pilot-license",
      name: "CV Employment Verification",
      description: "Employment history verification document",
      workflowCount: 1,
      fieldsCount: 9,
      checksCount: 2,
      sampleDocument: "/docs/cv_roberto.pdf",
    },
    tags: ["Manager Position", "Verified"],
  },
  {
    uuid: "doc-pl-002",
    name: "CV_Employment_Ana_Martinez_20240121.pdf",
    identifier: "EMP-AM-2024005",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-21T09:00:00Z",
    fileSize: 198456,
    mimeType: "application/pdf",
    workflowUuid: "ws-atc-processing",
    doctype: {
      uuid: "dt-pilot-license",
      name: "CV Employment Verification",
      description: "Employment history verification document",
      workflowCount: 1,
      fieldsCount: 9,
      checksCount: 2,
      sampleDocument: "/docs/cv_roberto.pdf",
    },
    tags: ["Senior Position", "Review Needed"],
  },

  // Sales Orders Ingestion Workflow (ws-sales-orders)
  {
    uuid: "doc-so-001",
    name: "SalesOrder_ACMECorp_SO2024-1543.pdf",
    identifier: "SO-2024-1543",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-20T11:30:00Z",
    confirmedAt: "2024-01-20T14:20:00Z",
    fileSize: 289345,
    mimeType: "application/pdf",
    workflowUuid: "ws-sales-orders",
    doctype: {
      uuid: "dt-sales-order",
      name: "Sales Order",
      description:
        "Commercial document confirming the sale of goods or services",
      workflowCount: 1,
      fieldsCount: 15,
      checksCount: 4,
      sampleDocument: "/docs/sales_order_1.pdf",
    },
    tags: ["Q1-2024", "Enterprise"],
    extractedData: {
      pdfUrl: "/docs/sales_order_1.pdf",
      extractedAt: "2024-01-20T11:35:00Z",
      processingTime: 4200,
      fields: [
        {
          fieldUuid: "field-so-1",
          fieldName: "Order Number",
          fieldType: "text",
          value: "SO-2024-1543",
          confidence: 0.99,
          validated: true,
        },
        {
          fieldUuid: "field-so-2",
          fieldName: "Order Date",
          fieldType: "date",
          value: "2024-01-15",
          confidence: 0.98,
          validated: true,
        },
        {
          fieldUuid: "field-so-3",
          fieldName: "Customer Name",
          fieldType: "text",
          value: "ACME Corporation",
          confidence: 0.97,
          validated: true,
        },
        {
          fieldUuid: "field-so-4",
          fieldName: "Customer ID",
          fieldType: "text",
          value: "CUST-10234",
          confidence: 0.96,
          validated: true,
        },
        {
          fieldUuid: "field-so-5",
          fieldName: "Subtotal",
          fieldType: "number",
          value: 45000.0,
          confidence: 0.98,
          validated: true,
        },
        {
          fieldUuid: "field-so-6",
          fieldName: "Tax Amount",
          fieldType: "number",
          value: 7200.0,
          confidence: 0.98,
          validated: true,
        },
        {
          fieldUuid: "field-so-7",
          fieldName: "Total Amount",
          fieldType: "number",
          value: 52200.0,
          confidence: 0.99,
          validated: true,
        },
        {
          fieldUuid: "field-so-8",
          fieldName: "Currency",
          fieldType: "text",
          value: "USD",
          confidence: 0.99,
          validated: true,
        },
        {
          fieldUuid: "field-so-9",
          fieldName: "Shipping Address",
          fieldType: "textarea",
          value: "123 Main Street, Suite 500, New York, NY 10001, USA",
          confidence: 0.94,
          validated: true,
        },
        {
          fieldUuid: "field-so-10",
          fieldName: "Delivery Date",
          fieldType: "date",
          value: "2024-02-15",
          confidence: 0.92,
          validated: true,
        },
      ],
    },
  },
  {
    uuid: "doc-so-002",
    name: "SalesOrder_GlobalTech_SO2024-1587.pdf",
    identifier: "SO-2024-1587",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-21T08:15:00Z",
    fileSize: 312456,
    mimeType: "application/pdf",
    workflowUuid: "ws-sales-orders",
    doctype: {
      uuid: "dt-sales-order",
      name: "Sales Order",
      description:
        "Commercial document confirming the sale of goods or services",
      workflowCount: 1,
      fieldsCount: 15,
      checksCount: 4,
      sampleDocument: "/docs/sales_order_1.pdf",
    },
    tags: ["Urgent"],
    extractedData: {
      pdfUrl: "/docs/sales_order_1.pdf",
      extractedAt: "2024-01-21T08:20:00Z",
      processingTime: 3800,
      fields: [
        {
          fieldUuid: "field-so-1",
          fieldName: "Order Number",
          fieldType: "text",
          value: "SO-2024-1587",
          confidence: 0.98,
          validated: true,
        },
        {
          fieldUuid: "field-so-2",
          fieldName: "Order Date",
          fieldType: "date",
          value: "2024-01-18",
          confidence: 0.95,
          validated: false,
        },
        {
          fieldUuid: "field-so-3",
          fieldName: "Customer Name",
          fieldType: "text",
          value: "GlobalTech Solutions Inc.",
          confidence: 0.96,
          validated: false,
        },
        {
          fieldUuid: "field-so-4",
          fieldName: "Customer ID",
          fieldType: "text",
          value: "CUST-20451",
          confidence: 0.89,
          validated: false,
        },
        {
          fieldUuid: "field-so-5",
          fieldName: "Subtotal",
          fieldType: "number",
          value: 128500.0,
          confidence: 0.93,
          validated: false,
        },
        {
          fieldUuid: "field-so-6",
          fieldName: "Tax Amount",
          fieldType: "number",
          value: 20560.0,
          confidence: 0.91,
          validated: false,
        },
        {
          fieldUuid: "field-so-7",
          fieldName: "Total Amount",
          fieldType: "number",
          value: 149060.0,
          confidence: 0.94,
          validated: false,
        },
        {
          fieldUuid: "field-so-8",
          fieldName: "Currency",
          fieldType: "text",
          value: "USD",
          confidence: 0.97,
          validated: true,
        },
        {
          fieldUuid: "field-so-9",
          fieldName: "Shipping Address",
          fieldType: "textarea",
          value:
            "4567 Technology Drive, Building C, San Francisco, CA 94107, USA",
          confidence: 0.88,
          validated: false,
        },
        {
          fieldUuid: "field-so-10",
          fieldName: "Delivery Date",
          fieldType: "date",
          value: "2024-03-01",
          confidence: 0.86,
          validated: false,
        },
      ],
    },
  },
  {
    uuid: "doc-so-003",
    name: "SalesOrder_TechSolutions_SO2024-1601.pdf",
    identifier: "SO-2024-1601",
    status: DocumentStatus.REJECTED,
    uploadedAt: "2024-01-19T16:45:00Z",
    fileSize: 198234,
    mimeType: "application/pdf",
    workflowUuid: "ws-sales-orders",
    doctype: {
      uuid: "dt-sales-order",
      name: "Sales Order",
      description:
        "Commercial document confirming the sale of goods or services",
      workflowCount: 1,
      fieldsCount: 15,
      checksCount: 4,
      sampleDocument: "/docs/sales_order_1.pdf",
    },
    tags: ["Rejected", "Incomplete"],
    extractedData: {
      pdfUrl: "/docs/sales_order_1.pdf",
      extractedAt: "2024-01-19T16:50:00Z",
      processingTime: 2900,
      fields: [
        {
          fieldUuid: "field-so-1",
          fieldName: "Order Number",
          fieldType: "text",
          value: "SO-2024-1601",
          confidence: 0.97,
          validated: true,
        },
        {
          fieldUuid: "field-so-2",
          fieldName: "Order Date",
          fieldType: "date",
          value: "2024-01-16",
          confidence: 0.92,
          validated: false,
        },
        {
          fieldUuid: "field-so-3",
          fieldName: "Customer Name",
          fieldType: "text",
          value: "Tech Solutions",
          confidence: 0.78,
          validated: false,
        },
        {
          fieldUuid: "field-so-4",
          fieldName: "Customer ID",
          fieldType: "text",
          value: "",
          confidence: 0.0,
          validated: false,
        },
        {
          fieldUuid: "field-so-5",
          fieldName: "Subtotal",
          fieldType: "number",
          value: 25000.0,
          confidence: 0.81,
          validated: false,
        },
        {
          fieldUuid: "field-so-6",
          fieldName: "Tax Amount",
          fieldType: "number",
          value: 3800.0,
          confidence: 0.75,
          validated: false,
        },
        {
          fieldUuid: "field-so-7",
          fieldName: "Total Amount",
          fieldType: "number",
          value: 28900.0,
          confidence: 0.83,
          validated: false,
        },
        {
          fieldUuid: "field-so-8",
          fieldName: "Currency",
          fieldType: "text",
          value: "US",
          confidence: 0.68,
          validated: false,
        },
        {
          fieldUuid: "field-so-9",
          fieldName: "Shipping Address",
          fieldType: "textarea",
          value: "",
          confidence: 0.0,
          validated: false,
        },
        {
          fieldUuid: "field-so-10",
          fieldName: "Delivery Date",
          fieldType: "date",
          value: "",
          confidence: 0.0,
          validated: false,
        },
      ],
    },
  },
  {
    uuid: "doc-pr-001",
    name: "PurchaseReq_IT_PR2024-0234.pdf",
    identifier: "PR-2024-0234",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-18T13:20:00Z",
    confirmedAt: "2024-01-19T10:00:00Z",
    fileSize: 167890,
    mimeType: "application/pdf",
    workflowUuid: "ws-sales-orders",
    doctype: {
      uuid: "dt-purchase-requisition",
      name: "Purchase Requisition",
      description:
        "Internal document requesting the purchase of goods or services",
      workflowCount: 1,
      fieldsCount: 11,
      checksCount: 3,
      sampleDocument: "/docs/invoice_1.pdf",
    },
    tags: ["IT Department"],
    extractedData: {
      pdfUrl: "/docs/invoice_1.pdf",
      extractedAt: "2024-01-18T13:25:00Z",
      processingTime: 3100,
      fields: [
        {
          fieldUuid: "field-pr-1",
          fieldName: "Requisition Number",
          fieldType: "text",
          value: "PR-2024-0234",
          confidence: 0.99,
          validated: true,
        },
        {
          fieldUuid: "field-pr-2",
          fieldName: "Requestor Name",
          fieldType: "text",
          value: "Michael Chen",
          confidence: 0.97,
          validated: true,
        },
        {
          fieldUuid: "field-pr-3",
          fieldName: "Department",
          fieldType: "text",
          value: "IT-Infrastructure",
          confidence: 0.96,
          validated: true,
        },
        {
          fieldUuid: "field-pr-4",
          fieldName: "Request Date",
          fieldType: "date",
          value: "2024-01-18",
          confidence: 0.98,
          validated: true,
        },
        {
          fieldUuid: "field-pr-5",
          fieldName: "Item Description",
          fieldType: "textarea",
          value:
            "Dell PowerEdge R750 Server - 2x Intel Xeon Silver 4314, 128GB RAM, 8TB SSD Storage",
          confidence: 0.94,
          validated: true,
        },
        {
          fieldUuid: "field-pr-6",
          fieldName: "Quantity",
          fieldType: "number",
          value: 5,
          confidence: 0.98,
          validated: true,
        },
        {
          fieldUuid: "field-pr-7",
          fieldName: "Estimated Cost",
          fieldType: "number",
          value: 47500.0,
          confidence: 0.95,
          validated: true,
        },
        {
          fieldUuid: "field-pr-8",
          fieldName: "Approver Name",
          fieldType: "text",
          value: "Sarah Johnson",
          confidence: 0.93,
          validated: true,
        },
        {
          fieldUuid: "field-pr-9",
          fieldName: "Approval Status",
          fieldType: "select",
          value: "Approved",
          confidence: 0.96,
          validated: true,
        },
      ],
    },
  },
  {
    uuid: "doc-pr-002",
    name: "PurchaseReq_Operations_PR2024-0287.pdf",
    identifier: "PR-2024-0287",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-21T10:30:00Z",
    fileSize: 189456,
    mimeType: "application/pdf",
    workflowUuid: "ws-sales-orders",
    doctype: {
      uuid: "dt-purchase-requisition",
      name: "Purchase Requisition",
      description:
        "Internal document requesting the purchase of goods or services",
      workflowCount: 1,
      fieldsCount: 11,
      checksCount: 3,
      sampleDocument: "/docs/invoice_1.pdf",
    },
    tags: ["Operations"],
    extractedData: {
      pdfUrl: "/docs/invoice_1.pdf",
      extractedAt: "2024-01-21T10:35:00Z",
      processingTime: 3600,
      fields: [
        {
          fieldUuid: "field-pr-1",
          fieldName: "Requisition Number",
          fieldType: "text",
          value: "PR-2024-0287",
          confidence: 0.98,
          validated: true,
        },
        {
          fieldUuid: "field-pr-2",
          fieldName: "Requestor Name",
          fieldType: "text",
          value: "Amanda Rodriguez",
          confidence: 0.94,
          validated: false,
        },
        {
          fieldUuid: "field-pr-3",
          fieldName: "Department",
          fieldType: "text",
          value: "Operations-Logistics",
          confidence: 0.91,
          validated: false,
        },
        {
          fieldUuid: "field-pr-4",
          fieldName: "Request Date",
          fieldType: "date",
          value: "2024-01-20",
          confidence: 0.95,
          validated: false,
        },
        {
          fieldUuid: "field-pr-5",
          fieldName: "Item Description",
          fieldType: "textarea",
          value:
            "Forklift Equipment - Toyota 8FGU25 Series, 5,000 lb capacity, LPG powered with side shifter",
          confidence: 0.88,
          validated: false,
        },
        {
          fieldUuid: "field-pr-6",
          fieldName: "Quantity",
          fieldType: "number",
          value: 3,
          confidence: 0.92,
          validated: false,
        },
        {
          fieldUuid: "field-pr-7",
          fieldName: "Estimated Cost",
          fieldType: "number",
          value: 89700.0,
          confidence: 0.87,
          validated: false,
        },
        {
          fieldUuid: "field-pr-8",
          fieldName: "Approver Name",
          fieldType: "text",
          value: "",
          confidence: 0.0,
          validated: false,
        },
        {
          fieldUuid: "field-pr-9",
          fieldName: "Approval Status",
          fieldType: "select",
          value: "Pending",
          confidence: 0.89,
          validated: false,
        },
      ],
    },
  },

  // Microcredit Requests Workflow (ws-microcredit)
  {
    uuid: "doc-mc-001",
    name: "MicrocreditApp_JuanPerez_MC2024-0156.pdf",
    identifier: "MC-2024-0156",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-20T09:45:00Z",
    fileSize: 345678,
    mimeType: "application/pdf",
    workflowUuid: "ws-microcredit",
    doctype: {
      uuid: "dt-microcredit-app",
      name: "Microcredit Application",
      description: "Application form for small business microcredit loans",
      workflowCount: 1,
      fieldsCount: 16,
      checksCount: 5,
      sampleDocument: "/docs/microcredit_request_1.pdf",
    },
    tags: ["Small Business", "Priority"],
  },
  {
    uuid: "doc-mc-002",
    name: "MicrocreditApp_AnaLopez_MC2024-0178.pdf",
    identifier: "MC-2024-0178",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-19T14:30:00Z",
    confirmedAt: "2024-01-20T11:00:00Z",
    fileSize: 298765,
    mimeType: "application/pdf",
    workflowUuid: "ws-microcredit",
    doctype: {
      uuid: "dt-microcredit-app",
      name: "Microcredit Application",
      description: "Application form for small business microcredit loans",
      workflowCount: 1,
      fieldsCount: 16,
      checksCount: 5,
      sampleDocument: "/docs/microcredit_request_1.pdf",
    },
    tags: ["Approved", "Q1-2024"],
  },
  {
    uuid: "doc-mc-003",
    name: "MicrocreditApp_CarlosRuiz_MC2024-0189.pdf",
    identifier: "MC-2024-0189",
    status: DocumentStatus.REJECTED,
    uploadedAt: "2024-01-18T11:20:00Z",
    fileSize: 267894,
    mimeType: "application/pdf",
    workflowUuid: "ws-microcredit",
    doctype: {
      uuid: "dt-microcredit-app",
      name: "Microcredit Application",
      description: "Application form for small business microcredit loans",
      workflowCount: 1,
      fieldsCount: 16,
      checksCount: 5,
      sampleDocument: "/docs/microcredit_request_1.pdf",
    },
    tags: ["Rejected", "Incomplete Documentation"],
  },
  {
    uuid: "doc-iv-001",
    name: "IncomeVerif_JuanPerez_IV2024-0156.pdf",
    identifier: "IV-2024-0156",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-20T10:00:00Z",
    confirmedAt: "2024-01-20T16:30:00Z",
    fileSize: 178234,
    mimeType: "application/pdf",
    workflowUuid: "ws-microcredit",
    doctype: {
      uuid: "dt-income-verification",
      name: "Income Verification",
      description: "Document verifying applicant's income sources and amounts",
      workflowCount: 1,
      fieldsCount: 10,
      checksCount: 3,
      sampleDocument: "/docs/cv_roberto.pdf",
    },
    tags: ["Verified"],
  },
  {
    uuid: "doc-iv-002",
    name: "IncomeVerif_AnaLopez_IV2024-0178.pdf",
    identifier: "IV-2024-0178",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-21T08:45:00Z",
    fileSize: 189456,
    mimeType: "application/pdf",
    workflowUuid: "ws-microcredit",
    doctype: {
      uuid: "dt-income-verification",
      name: "Income Verification",
      description: "Document verifying applicant's income sources and amounts",
      workflowCount: 1,
      fieldsCount: 10,
      checksCount: 3,
      sampleDocument: "/docs/cv_roberto.pdf",
    },
    tags: ["Pending Review"],
  },

  // Insurance Validation Workflow (ws-insurance)
  {
    uuid: "doc-mc-cert-001",
    name: "MedicalCert_PatientA_20240120.pdf",
    identifier: "MC-2024-A-0045",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-20T08:00:00Z",
    confirmedAt: "2024-01-20T12:30:00Z",
    fileSize: 234567,
    mimeType: "application/pdf",
    workflowUuid: "ws-insurance",
    doctype: {
      uuid: "dt-medical-cert",
      name: "Medical Certificate",
      description:
        "Official medical certificate issued by licensed healthcare professionals",
      workflowCount: 1,
      fieldsCount: 14,
      checksCount: 4,
      sampleDocument: "/docs/medic_cert_1.pdf",
    },
    tags: ["Work Absence", "Validated"],
  },
  {
    uuid: "doc-mc-cert-002",
    name: "MedicalCert_PatientB_20240121.pdf",
    identifier: "MC-2024-B-0052",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-21T09:30:00Z",
    fileSize: 198765,
    mimeType: "application/pdf",
    workflowUuid: "ws-insurance",
    doctype: {
      uuid: "dt-medical-cert",
      name: "Medical Certificate",
      description:
        "Official medical certificate issued by licensed healthcare professionals",
      workflowCount: 1,
      fieldsCount: 14,
      checksCount: 4,
      sampleDocument: "/docs/medic_cert_1.pdf",
    },
    tags: ["Surgery", "Pending"],
  },
  {
    uuid: "doc-mc-cert-003",
    name: "MedicalCert_PatientC_20240119.pdf",
    identifier: "MC-2024-C-0038",
    status: DocumentStatus.ARCHIVED,
    uploadedAt: "2024-01-15T11:20:00Z",
    confirmedAt: "2024-01-16T09:00:00Z",
    fileSize: 178234,
    mimeType: "application/pdf",
    workflowUuid: "ws-insurance",
    doctype: {
      uuid: "dt-medical-cert",
      name: "Medical Certificate",
      description:
        "Official medical certificate issued by licensed healthcare professionals",
      workflowCount: 1,
      fieldsCount: 14,
      checksCount: 4,
      sampleDocument: "/docs/medic_cert_1.pdf",
    },
    tags: ["Archived", "2024"],
  },
  {
    uuid: "doc-ic-001",
    name: "InsuranceClaim_ACC2024-0234.pdf",
    identifier: "CLM-2024-0234",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-20T13:15:00Z",
    fileSize: 456789,
    mimeType: "application/pdf",
    workflowUuid: "ws-insurance",
    doctype: {
      uuid: "dt-insurance-claim",
      name: "Insurance Claim Form",
      description: "Formal request for insurance coverage or compensation",
      workflowCount: 1,
      fieldsCount: 13,
      checksCount: 4,
      sampleDocument: "/docs/medic_cert_2.pdf",
    },
    tags: ["Accident", "High Priority"],
  },
  {
    uuid: "doc-ic-002",
    name: "InsuranceClaim_MED2024-0289.pdf",
    identifier: "CLM-2024-0289",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-19T10:45:00Z",
    confirmedAt: "2024-01-20T15:00:00Z",
    fileSize: 389456,
    mimeType: "application/pdf",
    workflowUuid: "ws-insurance",
    doctype: {
      uuid: "dt-insurance-claim",
      name: "Insurance Claim Form",
      description: "Formal request for insurance coverage or compensation",
      workflowCount: 1,
      fieldsCount: 13,
      checksCount: 4,
      sampleDocument: "/docs/medic_cert_2.pdf",
    },
    tags: ["Medical", "Approved"],
  },
  {
    uuid: "doc-ic-003",
    name: "InsuranceClaim_AUTO2024-0301.pdf",
    identifier: "CLM-2024-0301",
    status: DocumentStatus.REJECTED,
    uploadedAt: "2024-01-18T14:20:00Z",
    fileSize: 298765,
    mimeType: "application/pdf",
    workflowUuid: "ws-insurance",
    doctype: {
      uuid: "dt-insurance-claim",
      name: "Insurance Claim Form",
      description: "Formal request for insurance coverage or compensation",
      workflowCount: 1,
      fieldsCount: 13,
      checksCount: 4,
      sampleDocument: "/docs/medic_cert_2.pdf",
    },
    tags: ["Auto", "Rejected", "Fraud Suspected"],
  },

  // Blank Namespace Workflow (ws-blank)
  {
    uuid: "doc-new-001",
    name: "UnknownDocument_001.pdf",
    identifier: "UNK-2024-001",
    status: DocumentStatus.FOR_REVIEW,
    uploadedAt: "2024-01-21T11:00:00Z",
    fileSize: 123456,
    mimeType: "application/pdf",
    workflowUuid: "ws-blank",
    doctype: {
      uuid: "dt-new-document-type",
      name: "New Document Type",
      description: "",
      workflowCount: 1,
      fieldsCount: 0,
      checksCount: 0,
    },
    tags: ["Unclassified"],
  },
  {
    uuid: "doc-template-001",
    name: "Template_Invoice_Standard.pdf",
    identifier: "TPL-INV-STD",
    status: DocumentStatus.CONFIRMED,
    uploadedAt: "2024-01-15T10:00:00Z",
    confirmedAt: "2024-01-15T10:30:00Z",
    fileSize: 98765,
    mimeType: "application/pdf",
    workflowUuid: "ws-blank",
    doctype: {
      uuid: "dt-template-document",
      name: "Template Document",
      description: "Standard template document for creating new document types",
      workflowCount: 1,
      fieldsCount: 3,
      checksCount: 1,
      sampleDocument: "/docs/invoice_1.pdf",
    },
    tags: ["Template", "Standard"],
  },
];

export class MockDocumentRepository implements DocumentRepository {
  private documents: Document[] = [...mockDocuments];

  async getAll(
    workflowUuid: string
  ): Promise<DocumentListResponse | ErrorFeeback> {
    const workflowDocuments = this.documents.filter(
      (doc) => doc.workflowUuid === workflowUuid
    );
    return {
      data: workflowDocuments,
      datetime: new Date().toISOString(),
    };
  }

  async getById(uuid: string): Promise<DocumentResponse | ErrorFeeback> {
    const document = this.documents.find((doc) => doc.uuid === uuid);
    if (!document) {
      return {
        errors: [{ message: "Document not found", code: "NOT_FOUND" }],
        validation: null,
      };
    }
    return {
      data: document,
      datetime: new Date().toISOString(),
    };
  }

  async delete(uuid: string): Promise<TaskResultResponse | ErrorFeeback> {
    const index = this.documents.findIndex((doc) => doc.uuid === uuid);
    if (index === -1) {
      return {
        errors: [{ message: "Document not found", code: "NOT_FOUND" }],
        validation: null,
      };
    }
    this.documents.splice(index, 1);
    return successTask;
  }
}
