FROM node:22-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

COPY package.json pnpm-lock.yaml* .npmrc ./
RUN pnpm install

COPY . .

EXPOSE 4321
ENV HOST=0.0.0.0
ENV NODE_ENV=development

CMD ["pnpm", "dev"]
